project_name: fave

release:
  prerelease: auto
env:
  - GO111MODULE=on
  - CGO_ENABLED=1
before:
  hooks:
    - go mod download
builds:
  - id: fave-darwin-amd64
    main: ./cmd/fave-server
    binary: fave
    goos:
      - darwin
    goarch:
      - amd64
    env:
      - CC=o64-clang
      - CXX=o64-clang++
    flags:
      - -v
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/fairDataSociety/FaVe.commit={{ .ShortCommit }}
      - -X github.com/fairDataSociety/FaVe.version={{ .Version }}
  - id: fave-darwin-arm64
    main: ./cmd/fave-server
    binary: fave
    goos:
      - darwin
    goarch:
      - arm64
    env:
      - CC=oa64-clang
      - CXX=oa64-clang++
    flags:
      - -v
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/fairDataSociety/FaVe.commit={{ .ShortCommit }}
      - -X github.com/fairDataSociety/FaVe.version={{ .Version }}
  - id: fave-linux-amd64
    main: ./cmd/fave-server
    binary: fave
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CC=x86_64-linux-gnu-gcc
      - CXX=x86_64-linux-gnu-g++
    flags:
      - -v
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/fairDataSociety/FaVe.commit={{ .ShortCommit }}
      - -X github.com/fairDataSociety/FaVe.version={{ .Version }}
  - id: fave-linux-arm64
    main: ./cmd/fave-server
    binary: fave
    goos:
      - linux
    goarch:
      - arm64
    env:
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
    flags:
      - -v
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/fairDataSociety/FaVe.commit={{ .ShortCommit }}
      - -X github.com/fairDataSociety/FaVe.version={{ .Version }}
  - id: fave-windows-amd64
    main: ./cmd/fave-server
    binary: fave
    goos:
      - windows
    goarch:
      - amd64
    env:
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
    flags:
      - -v
      - -trimpath
      - -buildmode=exe
    ldflags:
      - -s -w
      - -X github.com/fairDataSociety/FaVe.commit={{ .ShortCommit }}
      - -X github.com/fairDataSociety/FaVe.version={{ .Version }}
archives:
  - id: binary-version
    name_template: '{{ .Binary }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}'
    format: binary
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-snapshot"
dockers:
  - image_templates:
      - "fairdatasociety/fave:v{{ .Version }}-amd64"
    use: buildx
    ids:
      - fave-linux-amd64
    goarch: amd64
    dockerfile: Dockerfile.goreleaser
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
  - image_templates:
      - "fairdatasociety/fave:v{{ .Version }}-arm64"
    use: buildx
    ids:
      - fave-linux-arm64
    goarch: arm64
    dockerfile: Dockerfile.goreleaser
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
docker_manifests:
  - name_template: fairdatasociety/fave:v{{ .Major }}.{{ .Minor }}.{{ .Patch }}{{ with .Prerelease }}-{{ . }}{{ end }}
    image_templates:
      - fairdatasociety/fave:v{{ .Version }}-amd64
      - fairdatasociety/fave:v{{ .Version }}-arm64
  - name_template: fairdatasociety/fave:latest
    image_templates:
      - fairdatasociety/fave:v{{ .Version }}-amd64
      - fairdatasociety/fave:v{{ .Version }}-arm64