// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/fairDataSociety/FaVe/models"
)

// FaveGetCollectionsOKCode is the HTTP code returned for type FaveGetCollectionsOK
const FaveGetCollectionsOKCode int = 200

/*
FaveGetCollectionsOK All collections

swagger:response faveGetCollectionsOK
*/
type FaveGetCollectionsOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Collection `json:"body,omitempty"`
}

// NewFaveGetCollectionsOK creates FaveGetCollectionsOK with default headers values
func NewFaveGetCollectionsOK() *FaveGetCollectionsOK {

	return &FaveGetCollectionsOK{}
}

// WithPayload adds the payload to the fave get collections o k response
func (o *FaveGetCollectionsOK) WithPayload(payload []*models.Collection) *FaveGetCollectionsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the fave get collections o k response
func (o *FaveGetCollectionsOK) SetPayload(payload []*models.Collection) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FaveGetCollectionsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Collection, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// FaveGetCollectionsBadRequestCode is the HTTP code returned for type FaveGetCollectionsBadRequest
const FaveGetCollectionsBadRequestCode int = 400

/*
FaveGetCollectionsBadRequest Malformed request.

swagger:response faveGetCollectionsBadRequest
*/
type FaveGetCollectionsBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewFaveGetCollectionsBadRequest creates FaveGetCollectionsBadRequest with default headers values
func NewFaveGetCollectionsBadRequest() *FaveGetCollectionsBadRequest {

	return &FaveGetCollectionsBadRequest{}
}

// WithPayload adds the payload to the fave get collections bad request response
func (o *FaveGetCollectionsBadRequest) WithPayload(payload *models.ErrorResponse) *FaveGetCollectionsBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the fave get collections bad request response
func (o *FaveGetCollectionsBadRequest) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FaveGetCollectionsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// FaveGetCollectionsUnauthorizedCode is the HTTP code returned for type FaveGetCollectionsUnauthorized
const FaveGetCollectionsUnauthorizedCode int = 401

/*
FaveGetCollectionsUnauthorized Unauthorized or invalid credentials.

swagger:response faveGetCollectionsUnauthorized
*/
type FaveGetCollectionsUnauthorized struct {
}

// NewFaveGetCollectionsUnauthorized creates FaveGetCollectionsUnauthorized with default headers values
func NewFaveGetCollectionsUnauthorized() *FaveGetCollectionsUnauthorized {

	return &FaveGetCollectionsUnauthorized{}
}

// WriteResponse to the client
func (o *FaveGetCollectionsUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// FaveGetCollectionsForbiddenCode is the HTTP code returned for type FaveGetCollectionsForbidden
const FaveGetCollectionsForbiddenCode int = 403

/*
FaveGetCollectionsForbidden Forbidden

swagger:response faveGetCollectionsForbidden
*/
type FaveGetCollectionsForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewFaveGetCollectionsForbidden creates FaveGetCollectionsForbidden with default headers values
func NewFaveGetCollectionsForbidden() *FaveGetCollectionsForbidden {

	return &FaveGetCollectionsForbidden{}
}

// WithPayload adds the payload to the fave get collections forbidden response
func (o *FaveGetCollectionsForbidden) WithPayload(payload *models.ErrorResponse) *FaveGetCollectionsForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the fave get collections forbidden response
func (o *FaveGetCollectionsForbidden) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FaveGetCollectionsForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// FaveGetCollectionsUnprocessableEntityCode is the HTTP code returned for type FaveGetCollectionsUnprocessableEntity
const FaveGetCollectionsUnprocessableEntityCode int = 422

/*
FaveGetCollectionsUnprocessableEntity Request body is well-formed (i.e., syntactically correct), but semantically erroneous.

swagger:response faveGetCollectionsUnprocessableEntity
*/
type FaveGetCollectionsUnprocessableEntity struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewFaveGetCollectionsUnprocessableEntity creates FaveGetCollectionsUnprocessableEntity with default headers values
func NewFaveGetCollectionsUnprocessableEntity() *FaveGetCollectionsUnprocessableEntity {

	return &FaveGetCollectionsUnprocessableEntity{}
}

// WithPayload adds the payload to the fave get collections unprocessable entity response
func (o *FaveGetCollectionsUnprocessableEntity) WithPayload(payload *models.ErrorResponse) *FaveGetCollectionsUnprocessableEntity {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the fave get collections unprocessable entity response
func (o *FaveGetCollectionsUnprocessableEntity) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FaveGetCollectionsUnprocessableEntity) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(422)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// FaveGetCollectionsInternalServerErrorCode is the HTTP code returned for type FaveGetCollectionsInternalServerError
const FaveGetCollectionsInternalServerErrorCode int = 500

/*
FaveGetCollectionsInternalServerError An error has occurred while trying to fulfill the request. Most likely the ErrorResponse will contain more information about the error.

swagger:response faveGetCollectionsInternalServerError
*/
type FaveGetCollectionsInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewFaveGetCollectionsInternalServerError creates FaveGetCollectionsInternalServerError with default headers values
func NewFaveGetCollectionsInternalServerError() *FaveGetCollectionsInternalServerError {

	return &FaveGetCollectionsInternalServerError{}
}

// WithPayload adds the payload to the fave get collections internal server error response
func (o *FaveGetCollectionsInternalServerError) WithPayload(payload *models.ErrorResponse) *FaveGetCollectionsInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the fave get collections internal server error response
func (o *FaveGetCollectionsInternalServerError) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FaveGetCollectionsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
