// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/fairDataSociety/FaVe/models"
)

// FaveAddDocumentsOKCode is the HTTP code returned for type FaveAddDocumentsOK
const FaveAddDocumentsOKCode int = 200

/*
FaveAddDocumentsOK collection added

swagger:response faveAddDocumentsOK
*/
type FaveAddDocumentsOK struct {

	/*
	  In: Body
	*/
	Payload *models.OKResponse `json:"body,omitempty"`
}

// NewFaveAddDocumentsOK creates FaveAddDocumentsOK with default headers values
func NewFaveAddDocumentsOK() *FaveAddDocumentsOK {

	return &FaveAddDocumentsOK{}
}

// WithPayload adds the payload to the fave add documents o k response
func (o *FaveAddDocumentsOK) WithPayload(payload *models.OKResponse) *FaveAddDocumentsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the fave add documents o k response
func (o *FaveAddDocumentsOK) SetPayload(payload *models.OKResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FaveAddDocumentsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// FaveAddDocumentsBadRequestCode is the HTTP code returned for type FaveAddDocumentsBadRequest
const FaveAddDocumentsBadRequestCode int = 400

/*
FaveAddDocumentsBadRequest Malformed request.

swagger:response faveAddDocumentsBadRequest
*/
type FaveAddDocumentsBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewFaveAddDocumentsBadRequest creates FaveAddDocumentsBadRequest with default headers values
func NewFaveAddDocumentsBadRequest() *FaveAddDocumentsBadRequest {

	return &FaveAddDocumentsBadRequest{}
}

// WithPayload adds the payload to the fave add documents bad request response
func (o *FaveAddDocumentsBadRequest) WithPayload(payload *models.ErrorResponse) *FaveAddDocumentsBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the fave add documents bad request response
func (o *FaveAddDocumentsBadRequest) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FaveAddDocumentsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// FaveAddDocumentsUnauthorizedCode is the HTTP code returned for type FaveAddDocumentsUnauthorized
const FaveAddDocumentsUnauthorizedCode int = 401

/*
FaveAddDocumentsUnauthorized Unauthorized or invalid credentials.

swagger:response faveAddDocumentsUnauthorized
*/
type FaveAddDocumentsUnauthorized struct {
}

// NewFaveAddDocumentsUnauthorized creates FaveAddDocumentsUnauthorized with default headers values
func NewFaveAddDocumentsUnauthorized() *FaveAddDocumentsUnauthorized {

	return &FaveAddDocumentsUnauthorized{}
}

// WriteResponse to the client
func (o *FaveAddDocumentsUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// FaveAddDocumentsForbiddenCode is the HTTP code returned for type FaveAddDocumentsForbidden
const FaveAddDocumentsForbiddenCode int = 403

/*
FaveAddDocumentsForbidden Forbidden

swagger:response faveAddDocumentsForbidden
*/
type FaveAddDocumentsForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewFaveAddDocumentsForbidden creates FaveAddDocumentsForbidden with default headers values
func NewFaveAddDocumentsForbidden() *FaveAddDocumentsForbidden {

	return &FaveAddDocumentsForbidden{}
}

// WithPayload adds the payload to the fave add documents forbidden response
func (o *FaveAddDocumentsForbidden) WithPayload(payload *models.ErrorResponse) *FaveAddDocumentsForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the fave add documents forbidden response
func (o *FaveAddDocumentsForbidden) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FaveAddDocumentsForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// FaveAddDocumentsUnprocessableEntityCode is the HTTP code returned for type FaveAddDocumentsUnprocessableEntity
const FaveAddDocumentsUnprocessableEntityCode int = 422

/*
FaveAddDocumentsUnprocessableEntity Request body is well-formed (i.e., syntactically correct), but semantically erroneous.

swagger:response faveAddDocumentsUnprocessableEntity
*/
type FaveAddDocumentsUnprocessableEntity struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewFaveAddDocumentsUnprocessableEntity creates FaveAddDocumentsUnprocessableEntity with default headers values
func NewFaveAddDocumentsUnprocessableEntity() *FaveAddDocumentsUnprocessableEntity {

	return &FaveAddDocumentsUnprocessableEntity{}
}

// WithPayload adds the payload to the fave add documents unprocessable entity response
func (o *FaveAddDocumentsUnprocessableEntity) WithPayload(payload *models.ErrorResponse) *FaveAddDocumentsUnprocessableEntity {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the fave add documents unprocessable entity response
func (o *FaveAddDocumentsUnprocessableEntity) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FaveAddDocumentsUnprocessableEntity) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(422)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// FaveAddDocumentsInternalServerErrorCode is the HTTP code returned for type FaveAddDocumentsInternalServerError
const FaveAddDocumentsInternalServerErrorCode int = 500

/*
FaveAddDocumentsInternalServerError An error has occurred while trying to fulfill the request. Most likely the ErrorResponse will contain more information about the error.

swagger:response faveAddDocumentsInternalServerError
*/
type FaveAddDocumentsInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewFaveAddDocumentsInternalServerError creates FaveAddDocumentsInternalServerError with default headers values
func NewFaveAddDocumentsInternalServerError() *FaveAddDocumentsInternalServerError {

	return &FaveAddDocumentsInternalServerError{}
}

// WithPayload adds the payload to the fave add documents internal server error response
func (o *FaveAddDocumentsInternalServerError) WithPayload(payload *models.ErrorResponse) *FaveAddDocumentsInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the fave add documents internal server error response
func (o *FaveAddDocumentsInternalServerError) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FaveAddDocumentsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
