// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/fairDataSociety/FaVe/models"
)

// FaveDeleteCollectionOKCode is the HTTP code returned for type FaveDeleteCollectionOK
const FaveDeleteCollectionOKCode int = 200

/*
FaveDeleteCollectionOK collection removed

swagger:response faveDeleteCollectionOK
*/
type FaveDeleteCollectionOK struct {
}

// NewFaveDeleteCollectionOK creates FaveDeleteCollectionOK with default headers values
func NewFaveDeleteCollectionOK() *FaveDeleteCollectionOK {

	return &FaveDeleteCollectionOK{}
}

// WriteResponse to the client
func (o *FaveDeleteCollectionOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// FaveDeleteCollectionBadRequestCode is the HTTP code returned for type FaveDeleteCollectionBadRequest
const FaveDeleteCollectionBadRequestCode int = 400

/*
FaveDeleteCollectionBadRequest Malformed request.

swagger:response faveDeleteCollectionBadRequest
*/
type FaveDeleteCollectionBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewFaveDeleteCollectionBadRequest creates FaveDeleteCollectionBadRequest with default headers values
func NewFaveDeleteCollectionBadRequest() *FaveDeleteCollectionBadRequest {

	return &FaveDeleteCollectionBadRequest{}
}

// WithPayload adds the payload to the fave delete collection bad request response
func (o *FaveDeleteCollectionBadRequest) WithPayload(payload *models.ErrorResponse) *FaveDeleteCollectionBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the fave delete collection bad request response
func (o *FaveDeleteCollectionBadRequest) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FaveDeleteCollectionBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// FaveDeleteCollectionUnauthorizedCode is the HTTP code returned for type FaveDeleteCollectionUnauthorized
const FaveDeleteCollectionUnauthorizedCode int = 401

/*
FaveDeleteCollectionUnauthorized Unauthorized or invalid credentials.

swagger:response faveDeleteCollectionUnauthorized
*/
type FaveDeleteCollectionUnauthorized struct {
}

// NewFaveDeleteCollectionUnauthorized creates FaveDeleteCollectionUnauthorized with default headers values
func NewFaveDeleteCollectionUnauthorized() *FaveDeleteCollectionUnauthorized {

	return &FaveDeleteCollectionUnauthorized{}
}

// WriteResponse to the client
func (o *FaveDeleteCollectionUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// FaveDeleteCollectionForbiddenCode is the HTTP code returned for type FaveDeleteCollectionForbidden
const FaveDeleteCollectionForbiddenCode int = 403

/*
FaveDeleteCollectionForbidden Forbidden

swagger:response faveDeleteCollectionForbidden
*/
type FaveDeleteCollectionForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewFaveDeleteCollectionForbidden creates FaveDeleteCollectionForbidden with default headers values
func NewFaveDeleteCollectionForbidden() *FaveDeleteCollectionForbidden {

	return &FaveDeleteCollectionForbidden{}
}

// WithPayload adds the payload to the fave delete collection forbidden response
func (o *FaveDeleteCollectionForbidden) WithPayload(payload *models.ErrorResponse) *FaveDeleteCollectionForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the fave delete collection forbidden response
func (o *FaveDeleteCollectionForbidden) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FaveDeleteCollectionForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// FaveDeleteCollectionUnprocessableEntityCode is the HTTP code returned for type FaveDeleteCollectionUnprocessableEntity
const FaveDeleteCollectionUnprocessableEntityCode int = 422

/*
FaveDeleteCollectionUnprocessableEntity Request body is well-formed (i.e., syntactically correct), but semantically erroneous.

swagger:response faveDeleteCollectionUnprocessableEntity
*/
type FaveDeleteCollectionUnprocessableEntity struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewFaveDeleteCollectionUnprocessableEntity creates FaveDeleteCollectionUnprocessableEntity with default headers values
func NewFaveDeleteCollectionUnprocessableEntity() *FaveDeleteCollectionUnprocessableEntity {

	return &FaveDeleteCollectionUnprocessableEntity{}
}

// WithPayload adds the payload to the fave delete collection unprocessable entity response
func (o *FaveDeleteCollectionUnprocessableEntity) WithPayload(payload *models.ErrorResponse) *FaveDeleteCollectionUnprocessableEntity {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the fave delete collection unprocessable entity response
func (o *FaveDeleteCollectionUnprocessableEntity) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FaveDeleteCollectionUnprocessableEntity) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(422)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// FaveDeleteCollectionInternalServerErrorCode is the HTTP code returned for type FaveDeleteCollectionInternalServerError
const FaveDeleteCollectionInternalServerErrorCode int = 500

/*
FaveDeleteCollectionInternalServerError An error has occurred while trying to fulfill the request. Most likely the ErrorResponse will contain more information about the error.

swagger:response faveDeleteCollectionInternalServerError
*/
type FaveDeleteCollectionInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewFaveDeleteCollectionInternalServerError creates FaveDeleteCollectionInternalServerError with default headers values
func NewFaveDeleteCollectionInternalServerError() *FaveDeleteCollectionInternalServerError {

	return &FaveDeleteCollectionInternalServerError{}
}

// WithPayload adds the payload to the fave delete collection internal server error response
func (o *FaveDeleteCollectionInternalServerError) WithPayload(payload *models.ErrorResponse) *FaveDeleteCollectionInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the fave delete collection internal server error response
func (o *FaveDeleteCollectionInternalServerError) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FaveDeleteCollectionInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
