// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// NewFaveGetDocumentsParams creates a new FaveGetDocumentsParams object
//
// There are no default values defined in the spec.
func NewFaveGetDocumentsParams() FaveGetDocumentsParams {

	return FaveGetDocumentsParams{}
}

// FaveGetDocumentsParams contains all the bound params for the fave get documents operation
// typically these are obtained from a http.Request
//
// swagger:parameters fave.getDocuments
type FaveGetDocumentsParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*The collection to use for this query
	  Required: true
	  In: query
	*/
	Collection string
	/*The property to filter the document by
	  Required: true
	  In: query
	*/
	Property string
	/*The value of the property to filter the document by
	  Required: true
	  In: query
	*/
	Value string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewFaveGetDocumentsParams() beforehand.
func (o *FaveGetDocumentsParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qCollection, qhkCollection, _ := qs.GetOK("collection")
	if err := o.bindCollection(qCollection, qhkCollection, route.Formats); err != nil {
		res = append(res, err)
	}

	qProperty, qhkProperty, _ := qs.GetOK("property")
	if err := o.bindProperty(qProperty, qhkProperty, route.Formats); err != nil {
		res = append(res, err)
	}

	qValue, qhkValue, _ := qs.GetOK("value")
	if err := o.bindValue(qValue, qhkValue, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindCollection binds and validates parameter Collection from query.
func (o *FaveGetDocumentsParams) bindCollection(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("collection", "query", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// AllowEmptyValue: false

	if err := validate.RequiredString("collection", "query", raw); err != nil {
		return err
	}
	o.Collection = raw

	return nil
}

// bindProperty binds and validates parameter Property from query.
func (o *FaveGetDocumentsParams) bindProperty(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("property", "query", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// AllowEmptyValue: false

	if err := validate.RequiredString("property", "query", raw); err != nil {
		return err
	}
	o.Property = raw

	return nil
}

// bindValue binds and validates parameter Value from query.
func (o *FaveGetDocumentsParams) bindValue(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("value", "query", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// AllowEmptyValue: false

	if err := validate.RequiredString("value", "query", raw); err != nil {
		return err
	}
	o.Value = raw

	return nil
}
