// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// FaveRootOKCode is the HTTP code returned for type FaveRootOK
const FaveRootOKCode int = 200

/*
FaveRootOK fave is alive and ready to serve content

swagger:response faveRootOK
*/
type FaveRootOK struct {
}

// NewFaveRootOK creates FaveRootOK with default headers values
func NewFaveRootOK() *FaveRootOK {

	return &FaveRootOK{}
}

// WriteResponse to the client
func (o *FaveRootOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
