// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// FaveRootHandlerFunc turns a function with the right signature into a fave root handler
type FaveRootHandlerFunc func(FaveRootParams) middleware.Responder

// Handle executing the request and returning a response
func (fn FaveRootHandlerFunc) Handle(params FaveRootParams) middleware.Responder {
	return fn(params)
}

// FaveRootHandler interface for that can handle valid fave root params
type FaveRootHandler interface {
	Handle(FaveRootParams) middleware.Responder
}

// NewFaveRoot creates a new http.Handler for the fave root operation
func NewFaveRoot(ctx *middleware.Context, handler FaveRootHandler) *FaveRoot {
	return &FaveRoot{Context: ctx, Handler: handler}
}

/*
	FaveRoot swagger:route GET / faveRoot

Home. Discover the REST API
*/
type FaveRoot struct {
	Context *middleware.Context
	Handler FaveRootHandler
}

func (o *FaveRoot) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewFaveRootParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
