// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// FaveGetCollectionsHandlerFunc turns a function with the right signature into a fave get collections handler
type FaveGetCollectionsHandlerFunc func(FaveGetCollectionsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn FaveGetCollectionsHandlerFunc) Handle(params FaveGetCollectionsParams) middleware.Responder {
	return fn(params)
}

// FaveGetCollectionsHandler interface for that can handle valid fave get collections params
type FaveGetCollectionsHandler interface {
	Handle(FaveGetCollectionsParams) middleware.Responder
}

// NewFaveGetCollections creates a new http.Handler for the fave get collections operation
func NewFaveGetCollections(ctx *middleware.Context, handler FaveGetCollectionsHandler) *FaveGetCollections {
	return &FaveGetCollections{Context: ctx, Handler: handler}
}

/*
	FaveGetCollections swagger:route GET /collections faveGetCollections

Get all collections.
*/
type FaveGetCollections struct {
	Context *middleware.Context
	Handler FaveGetCollectionsHandler
}

func (o *FaveGetCollections) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewFaveGetCollectionsParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
