// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/fairDataSociety/FaVe/models"
)

// FaveGetNearestDocumentsOKCode is the HTTP code returned for type FaveGetNearestDocumentsOK
const FaveGetNearestDocumentsOKCode int = 200

/*
FaveGetNearestDocumentsOK collection added

swagger:response faveGetNearestDocumentsOK
*/
type FaveGetNearestDocumentsOK struct {

	/*
	  In: Body
	*/
	Payload *models.NearestDocumentsResponse `json:"body,omitempty"`
}

// NewFaveGetNearestDocumentsOK creates FaveGetNearestDocumentsOK with default headers values
func NewFaveGetNearestDocumentsOK() *FaveGetNearestDocumentsOK {

	return &FaveGetNearestDocumentsOK{}
}

// WithPayload adds the payload to the fave get nearest documents o k response
func (o *FaveGetNearestDocumentsOK) WithPayload(payload *models.NearestDocumentsResponse) *FaveGetNearestDocumentsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the fave get nearest documents o k response
func (o *FaveGetNearestDocumentsOK) SetPayload(payload *models.NearestDocumentsResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FaveGetNearestDocumentsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// FaveGetNearestDocumentsBadRequestCode is the HTTP code returned for type FaveGetNearestDocumentsBadRequest
const FaveGetNearestDocumentsBadRequestCode int = 400

/*
FaveGetNearestDocumentsBadRequest Malformed request.

swagger:response faveGetNearestDocumentsBadRequest
*/
type FaveGetNearestDocumentsBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewFaveGetNearestDocumentsBadRequest creates FaveGetNearestDocumentsBadRequest with default headers values
func NewFaveGetNearestDocumentsBadRequest() *FaveGetNearestDocumentsBadRequest {

	return &FaveGetNearestDocumentsBadRequest{}
}

// WithPayload adds the payload to the fave get nearest documents bad request response
func (o *FaveGetNearestDocumentsBadRequest) WithPayload(payload *models.ErrorResponse) *FaveGetNearestDocumentsBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the fave get nearest documents bad request response
func (o *FaveGetNearestDocumentsBadRequest) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FaveGetNearestDocumentsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// FaveGetNearestDocumentsUnauthorizedCode is the HTTP code returned for type FaveGetNearestDocumentsUnauthorized
const FaveGetNearestDocumentsUnauthorizedCode int = 401

/*
FaveGetNearestDocumentsUnauthorized Unauthorized or invalid credentials.

swagger:response faveGetNearestDocumentsUnauthorized
*/
type FaveGetNearestDocumentsUnauthorized struct {
}

// NewFaveGetNearestDocumentsUnauthorized creates FaveGetNearestDocumentsUnauthorized with default headers values
func NewFaveGetNearestDocumentsUnauthorized() *FaveGetNearestDocumentsUnauthorized {

	return &FaveGetNearestDocumentsUnauthorized{}
}

// WriteResponse to the client
func (o *FaveGetNearestDocumentsUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// FaveGetNearestDocumentsForbiddenCode is the HTTP code returned for type FaveGetNearestDocumentsForbidden
const FaveGetNearestDocumentsForbiddenCode int = 403

/*
FaveGetNearestDocumentsForbidden Forbidden

swagger:response faveGetNearestDocumentsForbidden
*/
type FaveGetNearestDocumentsForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewFaveGetNearestDocumentsForbidden creates FaveGetNearestDocumentsForbidden with default headers values
func NewFaveGetNearestDocumentsForbidden() *FaveGetNearestDocumentsForbidden {

	return &FaveGetNearestDocumentsForbidden{}
}

// WithPayload adds the payload to the fave get nearest documents forbidden response
func (o *FaveGetNearestDocumentsForbidden) WithPayload(payload *models.ErrorResponse) *FaveGetNearestDocumentsForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the fave get nearest documents forbidden response
func (o *FaveGetNearestDocumentsForbidden) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FaveGetNearestDocumentsForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// FaveGetNearestDocumentsUnprocessableEntityCode is the HTTP code returned for type FaveGetNearestDocumentsUnprocessableEntity
const FaveGetNearestDocumentsUnprocessableEntityCode int = 422

/*
FaveGetNearestDocumentsUnprocessableEntity Request body is well-formed (i.e., syntactically correct), but semantically erroneous.

swagger:response faveGetNearestDocumentsUnprocessableEntity
*/
type FaveGetNearestDocumentsUnprocessableEntity struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewFaveGetNearestDocumentsUnprocessableEntity creates FaveGetNearestDocumentsUnprocessableEntity with default headers values
func NewFaveGetNearestDocumentsUnprocessableEntity() *FaveGetNearestDocumentsUnprocessableEntity {

	return &FaveGetNearestDocumentsUnprocessableEntity{}
}

// WithPayload adds the payload to the fave get nearest documents unprocessable entity response
func (o *FaveGetNearestDocumentsUnprocessableEntity) WithPayload(payload *models.ErrorResponse) *FaveGetNearestDocumentsUnprocessableEntity {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the fave get nearest documents unprocessable entity response
func (o *FaveGetNearestDocumentsUnprocessableEntity) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FaveGetNearestDocumentsUnprocessableEntity) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(422)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// FaveGetNearestDocumentsInternalServerErrorCode is the HTTP code returned for type FaveGetNearestDocumentsInternalServerError
const FaveGetNearestDocumentsInternalServerErrorCode int = 500

/*
FaveGetNearestDocumentsInternalServerError An error has occurred while trying to fulfill the request. Most likely the ErrorResponse will contain more information about the error.

swagger:response faveGetNearestDocumentsInternalServerError
*/
type FaveGetNearestDocumentsInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewFaveGetNearestDocumentsInternalServerError creates FaveGetNearestDocumentsInternalServerError with default headers values
func NewFaveGetNearestDocumentsInternalServerError() *FaveGetNearestDocumentsInternalServerError {

	return &FaveGetNearestDocumentsInternalServerError{}
}

// WithPayload adds the payload to the fave get nearest documents internal server error response
func (o *FaveGetNearestDocumentsInternalServerError) WithPayload(payload *models.ErrorResponse) *FaveGetNearestDocumentsInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the fave get nearest documents internal server error response
func (o *FaveGetNearestDocumentsInternalServerError) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FaveGetNearestDocumentsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
