// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// FaveDeleteCollectionHandlerFunc turns a function with the right signature into a fave delete collection handler
type FaveDeleteCollectionHandlerFunc func(FaveDeleteCollectionParams) middleware.Responder

// Handle executing the request and returning a response
func (fn FaveDeleteCollectionHandlerFunc) Handle(params FaveDeleteCollectionParams) middleware.Responder {
	return fn(params)
}

// FaveDeleteCollectionHandler interface for that can handle valid fave delete collection params
type FaveDeleteCollectionHandler interface {
	Handle(FaveDeleteCollectionParams) middleware.Responder
}

// NewFaveDeleteCollection creates a new http.Handler for the fave delete collection operation
func NewFaveDeleteCollection(ctx *middleware.Context, handler FaveDeleteCollectionHandler) *FaveDeleteCollection {
	return &FaveDeleteCollection{Context: ctx, Handler: handler}
}

/*
	FaveDeleteCollection swagger:route DELETE /collections/{collection} faveDeleteCollection

Delete a collection.
*/
type FaveDeleteCollection struct {
	Context *middleware.Context
	Handler FaveDeleteCollectionHandler
}

func (o *FaveDeleteCollection) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewFaveDeleteCollectionParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
