// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// FaveHelloOKCode is the HTTP code returned for type FaveHelloOK
const FaveHelloOKCode int = 200

/*
FaveHelloOK fave is alive and says hello

swagger:response faveHelloOK
*/
type FaveHelloOK struct {
}

// NewFaveHelloOK creates FaveHelloOK with default headers values
func NewFaveHelloOK() *FaveHelloOK {

	return &FaveHelloOK{}
}

// WriteResponse to the client
func (o *FaveHelloOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
