// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/fairDataSociety/FaVe/models"
)

// FaveGetDocumentsOKCode is the HTTP code returned for type FaveGetDocumentsOK
const FaveGetDocumentsOKCode int = 200

/*
FaveGetDocumentsOK Successful response

swagger:response faveGetDocumentsOK
*/
type FaveGetDocumentsOK struct {

	/*
	  In: Body
	*/
	Payload *models.Document `json:"body,omitempty"`
}

// NewFaveGetDocumentsOK creates FaveGetDocumentsOK with default headers values
func NewFaveGetDocumentsOK() *FaveGetDocumentsOK {

	return &FaveGetDocumentsOK{}
}

// WithPayload adds the payload to the fave get documents o k response
func (o *FaveGetDocumentsOK) WithPayload(payload *models.Document) *FaveGetDocumentsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the fave get documents o k response
func (o *FaveGetDocumentsOK) SetPayload(payload *models.Document) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FaveGetDocumentsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// FaveGetDocumentsBadRequestCode is the HTTP code returned for type FaveGetDocumentsBadRequest
const FaveGetDocumentsBadRequestCode int = 400

/*
FaveGetDocumentsBadRequest Malformed request.

swagger:response faveGetDocumentsBadRequest
*/
type FaveGetDocumentsBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewFaveGetDocumentsBadRequest creates FaveGetDocumentsBadRequest with default headers values
func NewFaveGetDocumentsBadRequest() *FaveGetDocumentsBadRequest {

	return &FaveGetDocumentsBadRequest{}
}

// WithPayload adds the payload to the fave get documents bad request response
func (o *FaveGetDocumentsBadRequest) WithPayload(payload *models.ErrorResponse) *FaveGetDocumentsBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the fave get documents bad request response
func (o *FaveGetDocumentsBadRequest) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FaveGetDocumentsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// FaveGetDocumentsNotFoundCode is the HTTP code returned for type FaveGetDocumentsNotFound
const FaveGetDocumentsNotFoundCode int = 404

/*
FaveGetDocumentsNotFound Document not found

swagger:response faveGetDocumentsNotFound
*/
type FaveGetDocumentsNotFound struct {
}

// NewFaveGetDocumentsNotFound creates FaveGetDocumentsNotFound with default headers values
func NewFaveGetDocumentsNotFound() *FaveGetDocumentsNotFound {

	return &FaveGetDocumentsNotFound{}
}

// WriteResponse to the client
func (o *FaveGetDocumentsNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
