// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// FaveAddDocumentsHandlerFunc turns a function with the right signature into a fave add documents handler
type FaveAddDocumentsHandlerFunc func(FaveAddDocumentsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn FaveAddDocumentsHandlerFunc) Handle(params FaveAddDocumentsParams) middleware.Responder {
	return fn(params)
}

// FaveAddDocumentsHandler interface for that can handle valid fave add documents params
type FaveAddDocumentsHandler interface {
	Handle(FaveAddDocumentsParams) middleware.Responder
}

// NewFaveAddDocuments creates a new http.Handler for the fave add documents operation
func NewFaveAddDocuments(ctx *middleware.Context, handler FaveAddDocumentsHandler) *FaveAddDocuments {
	return &FaveAddDocuments{Context: ctx, Handler: handler}
}

/*
	FaveAddDocuments swagger:route POST /documents faveAddDocuments

Add documents into a collection.
*/
type FaveAddDocuments struct {
	Context *middleware.Context
	Handler FaveAddDocumentsHandler
}

func (o *FaveAddDocuments) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewFaveAddDocumentsParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
