// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/fairDataSociety/FaVe/models"
)

// FaveGetNearestDocumentsByVectorOKCode is the HTTP code returned for type FaveGetNearestDocumentsByVectorOK
const FaveGetNearestDocumentsByVectorOKCode int = 200

/*
FaveGetNearestDocumentsByVectorOK collection added

swagger:response faveGetNearestDocumentsByVectorOK
*/
type FaveGetNearestDocumentsByVectorOK struct {

	/*
	  In: Body
	*/
	Payload *models.NearestDocumentsResponse `json:"body,omitempty"`
}

// NewFaveGetNearestDocumentsByVectorOK creates FaveGetNearestDocumentsByVectorOK with default headers values
func NewFaveGetNearestDocumentsByVectorOK() *FaveGetNearestDocumentsByVectorOK {

	return &FaveGetNearestDocumentsByVectorOK{}
}

// WithPayload adds the payload to the fave get nearest documents by vector o k response
func (o *FaveGetNearestDocumentsByVectorOK) WithPayload(payload *models.NearestDocumentsResponse) *FaveGetNearestDocumentsByVectorOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the fave get nearest documents by vector o k response
func (o *FaveGetNearestDocumentsByVectorOK) SetPayload(payload *models.NearestDocumentsResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FaveGetNearestDocumentsByVectorOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// FaveGetNearestDocumentsByVectorBadRequestCode is the HTTP code returned for type FaveGetNearestDocumentsByVectorBadRequest
const FaveGetNearestDocumentsByVectorBadRequestCode int = 400

/*
FaveGetNearestDocumentsByVectorBadRequest Malformed request.

swagger:response faveGetNearestDocumentsByVectorBadRequest
*/
type FaveGetNearestDocumentsByVectorBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewFaveGetNearestDocumentsByVectorBadRequest creates FaveGetNearestDocumentsByVectorBadRequest with default headers values
func NewFaveGetNearestDocumentsByVectorBadRequest() *FaveGetNearestDocumentsByVectorBadRequest {

	return &FaveGetNearestDocumentsByVectorBadRequest{}
}

// WithPayload adds the payload to the fave get nearest documents by vector bad request response
func (o *FaveGetNearestDocumentsByVectorBadRequest) WithPayload(payload *models.ErrorResponse) *FaveGetNearestDocumentsByVectorBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the fave get nearest documents by vector bad request response
func (o *FaveGetNearestDocumentsByVectorBadRequest) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FaveGetNearestDocumentsByVectorBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// FaveGetNearestDocumentsByVectorUnauthorizedCode is the HTTP code returned for type FaveGetNearestDocumentsByVectorUnauthorized
const FaveGetNearestDocumentsByVectorUnauthorizedCode int = 401

/*
FaveGetNearestDocumentsByVectorUnauthorized Unauthorized or invalid credentials.

swagger:response faveGetNearestDocumentsByVectorUnauthorized
*/
type FaveGetNearestDocumentsByVectorUnauthorized struct {
}

// NewFaveGetNearestDocumentsByVectorUnauthorized creates FaveGetNearestDocumentsByVectorUnauthorized with default headers values
func NewFaveGetNearestDocumentsByVectorUnauthorized() *FaveGetNearestDocumentsByVectorUnauthorized {

	return &FaveGetNearestDocumentsByVectorUnauthorized{}
}

// WriteResponse to the client
func (o *FaveGetNearestDocumentsByVectorUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// FaveGetNearestDocumentsByVectorForbiddenCode is the HTTP code returned for type FaveGetNearestDocumentsByVectorForbidden
const FaveGetNearestDocumentsByVectorForbiddenCode int = 403

/*
FaveGetNearestDocumentsByVectorForbidden Forbidden

swagger:response faveGetNearestDocumentsByVectorForbidden
*/
type FaveGetNearestDocumentsByVectorForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewFaveGetNearestDocumentsByVectorForbidden creates FaveGetNearestDocumentsByVectorForbidden with default headers values
func NewFaveGetNearestDocumentsByVectorForbidden() *FaveGetNearestDocumentsByVectorForbidden {

	return &FaveGetNearestDocumentsByVectorForbidden{}
}

// WithPayload adds the payload to the fave get nearest documents by vector forbidden response
func (o *FaveGetNearestDocumentsByVectorForbidden) WithPayload(payload *models.ErrorResponse) *FaveGetNearestDocumentsByVectorForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the fave get nearest documents by vector forbidden response
func (o *FaveGetNearestDocumentsByVectorForbidden) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FaveGetNearestDocumentsByVectorForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// FaveGetNearestDocumentsByVectorUnprocessableEntityCode is the HTTP code returned for type FaveGetNearestDocumentsByVectorUnprocessableEntity
const FaveGetNearestDocumentsByVectorUnprocessableEntityCode int = 422

/*
FaveGetNearestDocumentsByVectorUnprocessableEntity Request body is well-formed (i.e., syntactically correct), but semantically erroneous.

swagger:response faveGetNearestDocumentsByVectorUnprocessableEntity
*/
type FaveGetNearestDocumentsByVectorUnprocessableEntity struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewFaveGetNearestDocumentsByVectorUnprocessableEntity creates FaveGetNearestDocumentsByVectorUnprocessableEntity with default headers values
func NewFaveGetNearestDocumentsByVectorUnprocessableEntity() *FaveGetNearestDocumentsByVectorUnprocessableEntity {

	return &FaveGetNearestDocumentsByVectorUnprocessableEntity{}
}

// WithPayload adds the payload to the fave get nearest documents by vector unprocessable entity response
func (o *FaveGetNearestDocumentsByVectorUnprocessableEntity) WithPayload(payload *models.ErrorResponse) *FaveGetNearestDocumentsByVectorUnprocessableEntity {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the fave get nearest documents by vector unprocessable entity response
func (o *FaveGetNearestDocumentsByVectorUnprocessableEntity) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FaveGetNearestDocumentsByVectorUnprocessableEntity) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(422)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// FaveGetNearestDocumentsByVectorInternalServerErrorCode is the HTTP code returned for type FaveGetNearestDocumentsByVectorInternalServerError
const FaveGetNearestDocumentsByVectorInternalServerErrorCode int = 500

/*
FaveGetNearestDocumentsByVectorInternalServerError An error has occurred while trying to fulfill the request. Most likely the ErrorResponse will contain more information about the error.

swagger:response faveGetNearestDocumentsByVectorInternalServerError
*/
type FaveGetNearestDocumentsByVectorInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewFaveGetNearestDocumentsByVectorInternalServerError creates FaveGetNearestDocumentsByVectorInternalServerError with default headers values
func NewFaveGetNearestDocumentsByVectorInternalServerError() *FaveGetNearestDocumentsByVectorInternalServerError {

	return &FaveGetNearestDocumentsByVectorInternalServerError{}
}

// WithPayload adds the payload to the fave get nearest documents by vector internal server error response
func (o *FaveGetNearestDocumentsByVectorInternalServerError) WithPayload(payload *models.ErrorResponse) *FaveGetNearestDocumentsByVectorInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the fave get nearest documents by vector internal server error response
func (o *FaveGetNearestDocumentsByVectorInternalServerError) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FaveGetNearestDocumentsByVectorInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
