// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// FaveGetNearestDocumentsHandlerFunc turns a function with the right signature into a fave get nearest documents handler
type FaveGetNearestDocumentsHandlerFunc func(FaveGetNearestDocumentsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn FaveGetNearestDocumentsHandlerFunc) Handle(params FaveGetNearestDocumentsParams) middleware.Responder {
	return fn(params)
}

// FaveGetNearestDocumentsHandler interface for that can handle valid fave get nearest documents params
type FaveGetNearestDocumentsHandler interface {
	Handle(FaveGetNearestDocumentsParams) middleware.Responder
}

// NewFaveGetNearestDocuments creates a new http.Handler for the fave get nearest documents operation
func NewFaveGetNearestDocuments(ctx *middleware.Context, handler FaveGetNearestDocumentsHandler) *FaveGetNearestDocuments {
	return &FaveGetNearestDocuments{Context: ctx, Handler: handler}
}

/*
	FaveGetNearestDocuments swagger:route POST /nearest-documents faveGetNearestDocuments

Get nearest documents for a collection.
*/
type FaveGetNearestDocuments struct {
	Context *middleware.Context
	Handler FaveGetNearestDocumentsHandler
}

func (o *FaveGetNearestDocuments) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewFaveGetNearestDocumentsParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
