// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewFaveDeleteCollectionParams creates a new FaveDeleteCollectionParams object
//
// There are no default values defined in the spec.
func NewFaveDeleteCollectionParams() FaveDeleteCollectionParams {

	return FaveDeleteCollectionParams{}
}

// FaveDeleteCollectionParams contains all the bound params for the fave delete collection operation
// typically these are obtained from a http.Request
//
// swagger:parameters fave.deleteCollection
type FaveDeleteCollectionParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Collection name
	  Required: true
	  In: path
	*/
	Collection string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewFaveDeleteCollectionParams() beforehand.
func (o *FaveDeleteCollectionParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rCollection, rhkCollection, _ := route.Params.GetOK("collection")
	if err := o.bindCollection(rCollection, rhkCollection, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindCollection binds and validates parameter Collection from path.
func (o *FaveDeleteCollectionParams) bindCollection(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.Collection = raw

	return nil
}
