// Code generated by go-swagger; DO NOT EDIT.

// Package restapi fave
//
//	Schemes:
//	  http
//	Host: localhost
//	BasePath: /v1
//	Version: 0.0.0-prealpha
//	Contact: fave<sabyasachi@datafund.io> https://github.com/fairDataSociety/FaVe
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
