// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/yaml",
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "swagger": "2.0",
  "info": {
    "title": "fave",
    "contact": {
      "name": "fave",
      "url": "https://github.com/fairDataSociety/FaVe",
      "email": "sabyasachi@datafund.io"
    },
    "version": "1.19.0-prealpha"
  },
  "basePath": "/",
  "paths": {
    "/": {
      "get": {
        "description": "Home. Discover the REST API",
        "operationId": "fave.root",
        "responses": {
          "200": {
            "description": "fave is alive and ready to serve content"
          }
        }
      }
    },
    "/hello": {
      "get": {
        "description": "hello. Discover the REST API",
        "operationId": "fave.hello",
        "responses": {
          "200": {
            "description": "fave is alive and says hello"
          }
        }
      }
    }
  },
  "definitions": {
    "ErrorResponse": {
      "description": "An error response given by FaVe end-points.",
      "type": "object",
      "properties": {
        "error": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "message": {
                "type": "string"
              }
            }
          }
        }
      }
    }
  },
  "tags": [
    {
      "description": "Everything about your fave",
      "name": "fave"
    }
  ],
  "externalDocs": {
    "url": "https://github.com/fairDataSociety/FaVe"
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json",
    "application/yaml"
  ],
  "produces": [
    "application/json"
  ],
  "swagger": "2.0",
  "info": {
    "title": "fave",
    "contact": {
      "name": "fave",
      "url": "https://github.com/fairDataSociety/FaVe",
      "email": "sabyasachi@datafund.io"
    },
    "version": "1.19.0-prealpha"
  },
  "basePath": "/",
  "paths": {
    "/": {
      "get": {
        "description": "Home. Discover the REST API",
        "operationId": "fave.root",
        "responses": {
          "200": {
            "description": "fave is alive and ready to serve content"
          }
        }
      }
    },
    "/hello": {
      "get": {
        "description": "hello. Discover the REST API",
        "operationId": "fave.hello",
        "responses": {
          "200": {
            "description": "fave is alive and says hello"
          }
        }
      }
    }
  },
  "definitions": {
    "ErrorResponse": {
      "description": "An error response given by FaVe end-points.",
      "type": "object",
      "properties": {
        "error": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/ErrorResponseErrorItems0"
          }
        }
      }
    },
    "ErrorResponseErrorItems0": {
      "type": "object",
      "properties": {
        "message": {
          "type": "string"
        }
      }
    }
  },
  "tags": [
    {
      "description": "Everything about your fave",
      "name": "fave"
    }
  ],
  "externalDocs": {
    "url": "https://github.com/fairDataSociety/FaVe"
  }
}`))
}
