// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/yaml",
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "swagger": "2.0",
  "info": {
    "title": "fave",
    "contact": {
      "name": "fave",
      "url": "https://github.com/fairDataSociety/FaVe",
      "email": "sabyasachi@datafund.io"
    },
    "version": "0.0.0-prealpha"
  },
  "basePath": "/v1",
  "paths": {
    "/": {
      "get": {
        "description": "Home. Discover the REST API",
        "operationId": "fave.root",
        "responses": {
          "200": {
            "description": "fave is alive and ready to serve content"
          }
        }
      }
    },
    "/collections": {
      "post": {
        "description": "Create a new collection.",
        "operationId": "fave.createCollection",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Collection"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "collection added",
            "schema": {
              "$ref": "#/definitions/OKResponse"
            }
          },
          "400": {
            "description": "Malformed request.",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "401": {
            "description": "Unauthorized or invalid credentials."
          },
          "403": {
            "description": "Forbidden",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "422": {
            "description": "Request body is well-formed (i.e., syntactically correct), but semantically erroneous.",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "500": {
            "description": "An error has occurred while trying to fulfill the request. Most likely the ErrorResponse will contain more information about the error.",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/collections/{collection}": {
      "delete": {
        "description": "Delete a collection.",
        "operationId": "fave.deleteCollection",
        "parameters": [
          {
            "type": "string",
            "description": "Collection name",
            "name": "collection",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "collection removed",
            "schema": {
              "$ref": "#/definitions/OKResponse"
            }
          },
          "400": {
            "description": "Malformed request.",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "401": {
            "description": "Unauthorized or invalid credentials."
          },
          "403": {
            "description": "Forbidden",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "422": {
            "description": "Request body is well-formed (i.e., syntactically correct), but semantically erroneous.",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "500": {
            "description": "An error has occurred while trying to fulfill the request. Most likely the ErrorResponse will contain more information about the error.",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/documents": {
      "get": {
        "description": "Retrieve a document based on query parameters",
        "operationId": "fave.getDocuments",
        "parameters": [
          {
            "type": "string",
            "description": "The property to filter the document by",
            "name": "property",
            "in": "query",
            "required": true
          },
          {
            "type": "string",
            "description": "The value of the property to filter the document by",
            "name": "value",
            "in": "query",
            "required": true
          },
          {
            "type": "string",
            "description": "The collection to use for this query",
            "name": "collection",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "schema": {
              "$ref": "#/definitions/Document"
            }
          },
          "400": {
            "description": "Malformed request.",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "404": {
            "description": "Document not found"
          }
        }
      },
      "post": {
        "description": "Add documents into a collection.",
        "operationId": "fave.addDocuments",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/AddDocumentsRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "collection added",
            "schema": {
              "$ref": "#/definitions/OKResponse"
            }
          },
          "400": {
            "description": "Malformed request.",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "401": {
            "description": "Unauthorized or invalid credentials."
          },
          "403": {
            "description": "Forbidden",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "422": {
            "description": "Request body is well-formed (i.e., syntactically correct), but semantically erroneous.",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "500": {
            "description": "An error has occurred while trying to fulfill the request. Most likely the ErrorResponse will contain more information about the error.",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/nearest-documents": {
      "post": {
        "description": "Get nearest documents for a collection.",
        "operationId": "fave.getNearestDocuments",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/NearestDocumentsRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "collection added",
            "schema": {
              "$ref": "#/definitions/NearestDocumentsResponse"
            }
          },
          "400": {
            "description": "Malformed request.",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "401": {
            "description": "Unauthorized or invalid credentials."
          },
          "403": {
            "description": "Forbidden",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "422": {
            "description": "Request body is well-formed (i.e., syntactically correct), but semantically erroneous.",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "500": {
            "description": "An error has occurred while trying to fulfill the request. Most likely the ErrorResponse will contain more information about the error.",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "AddDocumentsRequest": {
      "description": "Add the documents to the collection.",
      "type": "object",
      "properties": {
        "documents": {
          "description": "The actual list of Objects.",
          "type": "array",
          "items": {
            "$ref": "#/definitions/Document"
          }
        },
        "name": {
          "description": "Name of the collection as URI relative to the schema URL.",
          "type": "string"
        },
        "propertiesToVectorize": {
          "description": "Array of property names to be vectorized.",
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "Collection": {
      "type": "object",
      "properties": {
        "indexes": {
          "description": "The indexes of the collection for fairOS-dfs document store.",
          "type": "array",
          "items": {
            "$ref": "#/definitions/Index"
          }
        },
        "name": {
          "description": "Name of the collection",
          "type": "string"
        }
      }
    },
    "Document": {
      "type": "object",
      "properties": {
        "id": {
          "description": "ID of the Object.",
          "type": "string",
          "format": "uuid"
        },
        "properties": {
          "$ref": "#/definitions/Property"
        }
      }
    },
    "ErrorResponse": {
      "description": "An error response given by FaVe end-points.",
      "type": "object",
      "properties": {
        "error": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "message": {
                "type": "string"
              }
            }
          }
        }
      }
    },
    "Index": {
      "description": "This is an object for specifying which fields to index in fairOS document store while Collection creation",
      "type": "object",
      "properties": {
        "fieldName": {
          "description": "The filed name to index",
          "type": "string"
        },
        "fieldType": {
          "description": "Type of the field to index. Types can be \"string\", \"number\", \"map\", \"list\"",
          "type": "string"
        }
      }
    },
    "NearestDocumentsRequest": {
      "description": "Get the nearest documents from the collection.",
      "type": "object",
      "properties": {
        "distance": {
          "type": "number",
          "format": "float"
        },
        "limit": {
          "type": "number",
          "format": "int"
        },
        "name": {
          "description": "Name of the collection as URI relative to the schema URL.",
          "type": "string"
        },
        "text": {
          "description": "The text to search for.",
          "type": "string"
        }
      }
    },
    "NearestDocumentsResponse": {
      "description": "Response for the Nearest documents request",
      "type": "object",
      "properties": {
        "documents": {
          "description": "The actual list of Objects.",
          "type": "array",
          "items": {
            "$ref": "#/definitions/Document"
          }
        },
        "name": {
          "description": "Name of the collection as URI relative to the schema URL.",
          "type": "string"
        }
      }
    },
    "OKResponse": {
      "description": "An ok response given by FaVe end-points.",
      "type": "object",
      "properties": {
        "message": {
          "type": "string"
        }
      }
    },
    "Property": {
      "description": "This is an open object, with OpenAPI Specification 3.0 this will be more detailed.",
      "type": "object",
      "additionalProperties": true
    }
  },
  "tags": [
    {
      "description": "Everything about your fave",
      "name": "fave"
    }
  ],
  "externalDocs": {
    "url": "https://github.com/fairDataSociety/FaVe"
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json",
    "application/yaml"
  ],
  "produces": [
    "application/json"
  ],
  "swagger": "2.0",
  "info": {
    "title": "fave",
    "contact": {
      "name": "fave",
      "url": "https://github.com/fairDataSociety/FaVe",
      "email": "sabyasachi@datafund.io"
    },
    "version": "0.0.0-prealpha"
  },
  "basePath": "/v1",
  "paths": {
    "/": {
      "get": {
        "description": "Home. Discover the REST API",
        "operationId": "fave.root",
        "responses": {
          "200": {
            "description": "fave is alive and ready to serve content"
          }
        }
      }
    },
    "/collections": {
      "post": {
        "description": "Create a new collection.",
        "operationId": "fave.createCollection",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Collection"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "collection added",
            "schema": {
              "$ref": "#/definitions/OKResponse"
            }
          },
          "400": {
            "description": "Malformed request.",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "401": {
            "description": "Unauthorized or invalid credentials."
          },
          "403": {
            "description": "Forbidden",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "422": {
            "description": "Request body is well-formed (i.e., syntactically correct), but semantically erroneous.",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "500": {
            "description": "An error has occurred while trying to fulfill the request. Most likely the ErrorResponse will contain more information about the error.",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/collections/{collection}": {
      "delete": {
        "description": "Delete a collection.",
        "operationId": "fave.deleteCollection",
        "parameters": [
          {
            "type": "string",
            "description": "Collection name",
            "name": "collection",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "collection removed",
            "schema": {
              "$ref": "#/definitions/OKResponse"
            }
          },
          "400": {
            "description": "Malformed request.",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "401": {
            "description": "Unauthorized or invalid credentials."
          },
          "403": {
            "description": "Forbidden",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "422": {
            "description": "Request body is well-formed (i.e., syntactically correct), but semantically erroneous.",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "500": {
            "description": "An error has occurred while trying to fulfill the request. Most likely the ErrorResponse will contain more information about the error.",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/documents": {
      "get": {
        "description": "Retrieve a document based on query parameters",
        "operationId": "fave.getDocuments",
        "parameters": [
          {
            "type": "string",
            "description": "The property to filter the document by",
            "name": "property",
            "in": "query",
            "required": true
          },
          {
            "type": "string",
            "description": "The value of the property to filter the document by",
            "name": "value",
            "in": "query",
            "required": true
          },
          {
            "type": "string",
            "description": "The collection to use for this query",
            "name": "collection",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "schema": {
              "$ref": "#/definitions/Document"
            }
          },
          "400": {
            "description": "Malformed request.",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "404": {
            "description": "Document not found"
          }
        }
      },
      "post": {
        "description": "Add documents into a collection.",
        "operationId": "fave.addDocuments",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/AddDocumentsRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "collection added",
            "schema": {
              "$ref": "#/definitions/OKResponse"
            }
          },
          "400": {
            "description": "Malformed request.",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "401": {
            "description": "Unauthorized or invalid credentials."
          },
          "403": {
            "description": "Forbidden",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "422": {
            "description": "Request body is well-formed (i.e., syntactically correct), but semantically erroneous.",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "500": {
            "description": "An error has occurred while trying to fulfill the request. Most likely the ErrorResponse will contain more information about the error.",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/nearest-documents": {
      "post": {
        "description": "Get nearest documents for a collection.",
        "operationId": "fave.getNearestDocuments",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/NearestDocumentsRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "collection added",
            "schema": {
              "$ref": "#/definitions/NearestDocumentsResponse"
            }
          },
          "400": {
            "description": "Malformed request.",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "401": {
            "description": "Unauthorized or invalid credentials."
          },
          "403": {
            "description": "Forbidden",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "422": {
            "description": "Request body is well-formed (i.e., syntactically correct), but semantically erroneous.",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "500": {
            "description": "An error has occurred while trying to fulfill the request. Most likely the ErrorResponse will contain more information about the error.",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "AddDocumentsRequest": {
      "description": "Add the documents to the collection.",
      "type": "object",
      "properties": {
        "documents": {
          "description": "The actual list of Objects.",
          "type": "array",
          "items": {
            "$ref": "#/definitions/Document"
          }
        },
        "name": {
          "description": "Name of the collection as URI relative to the schema URL.",
          "type": "string"
        },
        "propertiesToVectorize": {
          "description": "Array of property names to be vectorized.",
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "Collection": {
      "type": "object",
      "properties": {
        "indexes": {
          "description": "The indexes of the collection for fairOS-dfs document store.",
          "type": "array",
          "items": {
            "$ref": "#/definitions/Index"
          }
        },
        "name": {
          "description": "Name of the collection",
          "type": "string"
        }
      }
    },
    "Document": {
      "type": "object",
      "properties": {
        "id": {
          "description": "ID of the Object.",
          "type": "string",
          "format": "uuid"
        },
        "properties": {
          "$ref": "#/definitions/Property"
        }
      }
    },
    "ErrorResponse": {
      "description": "An error response given by FaVe end-points.",
      "type": "object",
      "properties": {
        "error": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/ErrorResponseErrorItems0"
          }
        }
      }
    },
    "ErrorResponseErrorItems0": {
      "type": "object",
      "properties": {
        "message": {
          "type": "string"
        }
      }
    },
    "Index": {
      "description": "This is an object for specifying which fields to index in fairOS document store while Collection creation",
      "type": "object",
      "properties": {
        "fieldName": {
          "description": "The filed name to index",
          "type": "string"
        },
        "fieldType": {
          "description": "Type of the field to index. Types can be \"string\", \"number\", \"map\", \"list\"",
          "type": "string"
        }
      }
    },
    "NearestDocumentsRequest": {
      "description": "Get the nearest documents from the collection.",
      "type": "object",
      "properties": {
        "distance": {
          "type": "number",
          "format": "float"
        },
        "limit": {
          "type": "number",
          "format": "int"
        },
        "name": {
          "description": "Name of the collection as URI relative to the schema URL.",
          "type": "string"
        },
        "text": {
          "description": "The text to search for.",
          "type": "string"
        }
      }
    },
    "NearestDocumentsResponse": {
      "description": "Response for the Nearest documents request",
      "type": "object",
      "properties": {
        "documents": {
          "description": "The actual list of Objects.",
          "type": "array",
          "items": {
            "$ref": "#/definitions/Document"
          }
        },
        "name": {
          "description": "Name of the collection as URI relative to the schema URL.",
          "type": "string"
        }
      }
    },
    "OKResponse": {
      "description": "An ok response given by FaVe end-points.",
      "type": "object",
      "properties": {
        "message": {
          "type": "string"
        }
      }
    },
    "Property": {
      "description": "This is an open object, with OpenAPI Specification 3.0 this will be more detailed.",
      "type": "object",
      "additionalProperties": true
    }
  },
  "tags": [
    {
      "description": "Everything about your fave",
      "name": "fave"
    }
  ],
  "externalDocs": {
    "url": "https://github.com/fairDataSociety/FaVe"
  }
}`))
}
