// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Collection collection
//
// swagger:model Collection
type Collection struct {

	// The indexes of the collection.
	Indexes interface{} `json:"indexes,omitempty" yaml:"indexes,omitempty"`

	// Name of the collection as URI relative to the schema URL.
	Name string `json:"name,omitempty" yaml:"name,omitempty"`
}

// Validate validates this collection
func (m *Collection) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this collection based on context it is used
func (m *Collection) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Collection) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Collection) UnmarshalBinary(b []byte) error {
	var res Collection
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
