// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Index This is an object for specifying which fields to index in fairOS document store while Collection creation
//
// swagger:model Index
type Index struct {

	// The filed name to index
	FieldName string `json:"fieldName,omitempty" yaml:"fieldName,omitempty"`

	// Type of the field to index. Types can be "string", "number", "map", "list"
	FieldType string `json:"fieldType,omitempty" yaml:"fieldType,omitempty"`
}

// Validate validates this index
func (m *Index) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this index based on context it is used
func (m *Index) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Index) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Index) UnmarshalBinary(b []byte) error {
	var res Index
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
