// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NearestDocumentsRequest Get the nearest documents from the collection.
//
// swagger:model NearestDocumentsRequest
type NearestDocumentsRequest struct {

	// distance
	Distance float32 `json:"distance,omitempty" yaml:"distance,omitempty"`

	// Name of the collection as URI relative to the schema URL.
	Name string `json:"name,omitempty" yaml:"name,omitempty"`

	// The text to search for.
	Text string `json:"text,omitempty" yaml:"text,omitempty"`
}

// Validate validates this nearest documents request
func (m *NearestDocumentsRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this nearest documents request based on context it is used
func (m *NearestDocumentsRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *NearestDocumentsRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NearestDocumentsRequest) UnmarshalBinary(b []byte) error {
	var res NearestDocumentsRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
