// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// PropertySchema This is an open object, with OpenAPI Specification 3.0 this will be more detailed.
//
// swagger:model PropertySchema
type PropertySchema interface{}
