// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// VectorNearestDocumentsRequest Get the nearest documents from the collection.
//
// swagger:model VectorNearestDocumentsRequest
type VectorNearestDocumentsRequest struct {

	// distance
	Distance float32 `json:"distance,omitempty" yaml:"distance,omitempty"`

	// limit
	Limit int64 `json:"limit,omitempty" yaml:"limit,omitempty"`

	// Name of the collection
	Name string `json:"name,omitempty" yaml:"name,omitempty"`

	// The vector to search for
	Vector []float64 `json:"vector" yaml:"vector"`
}

// Validate validates this vector nearest documents request
func (m *VectorNearestDocumentsRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this vector nearest documents request based on context it is used
func (m *VectorNearestDocumentsRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *VectorNearestDocumentsRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VectorNearestDocumentsRequest) UnmarshalBinary(b []byte) error {
	var res VectorNearestDocumentsRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
